### ISSUE TITLE
"BiglyBT Update Support" missing/unavailable from website (Cannot restart)

### ISSUE THREAD

**Issue by fizzfaldt** [BiglySoftware/BiglyBT#2172]
I was getting errors about being unable to restart biglybt since azupdater is not installed.

Going to https://plugins.biglybt.com/
Tried to install/download "BiglyBT Update Support"
Download gives an access denied error, install says it's not found on the website.

This is clearly a problem with the website (possibly file permissions, maybe file is actually missing/not uploaded properly?)

Using Ubuntu 20.04
Using biglybt 2.2.0.2

![install-error](https://user-images.githubusercontent.com/2748321/126881095-da089673-d0f7-47ca-bf19-db28ab2dae3c.png)
![update-plugin](https://user-images.githubusercontent.com/2748321/126881096-274cea3d-693e-448c-8efd-85959b4100ef.png)
![access-denied](https://user-images.githubusercontent.com/2748321/126881097-c0750037-427b-4dab-a146-3355e57f275d.png)

**Comment by parg** [comment]
That plugin is supposed to be auto-installed, it isn't like any of the other plugins... I'll take a look

**Comment by parg** [comment]
Can't easily fix this - the plugin will be auto-installed if you run BiglyBT as administrator (on Windows at least, I would assume something similar on Linux). This is because it has to be a 'shared plugin' and thus installed into the BiglyBT application directory/plugins (which on Windows is not normally writeable).

I've fixed it up so you can download the plugin from https://plugins.biglybt.com/ - this gives you a .biglybt file containing the plugin which you can attempt to install via the File menu in BiglyBT. The problem is that if it needs admin/root access to install the plugin it will attempt to restart to gain admin priv to do this but can't restart because the plugin is required to restart....

**Comment by parg** [comment]
You can manually install it by grabbing

https://biglybt-files.s3.amazonaws.com/plugins/azupdater_2.1.zip

and unzipping into {install folder}/plugins/azupdater

**Comment by fizzfaldt** [comment]
Hmmm... I was able to install it shared by putting it into /usr/share/biglybt/plugins/azupdater
and that got me further, but still can't restart.

e.g. before following your instructions/getting it installed as shared.... "Restart" would do nothing... it just stays running.  Exit/Quit would work (but if I tried and failed to Restart first, then the quit button is just ignored)

After getting it installed shared, then "restart" just shuts it down (does not auto-restart)

This happens even on a clean install (e.g. purge followed by moving my ~/.biglybt directory away)

**Comment by parg** [comment]
Hmm, I just noticed you said you were running BiglyBT 2.2.0.2? The latest is 2.8.0.0  - can you try running the installer from https://www.biglybt.com/ ?

**Comment by fizzfaldt** [comment]
I had to uninstall Oracle java 13 and install openjdk 1.8  but finally got that installer working.


Restart works correctly with 2.8.0.0

**Comment by fizzfaldt** [comment]
I guess biglybt installer doesn't like oracle java
```./BiglyBT_Installer.sh 
don't need JNA
not wayland
No suitable Java Virtual Machine could be found on your system.
The version of the JVM must be 1.8.
Please define INSTALL4J_JAVA_HOME to point to a suitable JVM.```

**Comment by parg** [comment]
Hmm, BiglyBT itself runs fine on Java 13 and above, I'll check on that.
